### ISSUE TITLE
Does it support the use of 2D skeletal data sets?？

### ISSUE THREAD

**Issue by zjzhengyin** [huguyuehuhu/HCN-pytorch#18]
Hello, does your code support 2D skeleton dataset?Because I saw that the experimental part of the paper only used all kinds of 3D skeletal data sets.

**Comment by huguyuehuhu** [comment]
Yes， you only need to change the default input channel in model from 3 to 2.

**Comment by Jagadish-Kumaran** [comment]
> Yes， you only need to change the default input channel in model from 3 to 2.

Should I change this before training the model?

**Comment by huguyuehuhu** [comment]
> > Yes， you only need to change the default input channel in model from 3 to 2.
> 
> Should I change this before training the model?

yes

**Comment by Jagadish-Kumaran** [comment]
Dear Sir

Thanks very much for your reply. The objective of my project is to test the
model trained on NTU RGBD dataset on new youtube videos and detect the
action "hand touch head".

In OpenPose, I could only generate 2D pose key points from videos. But the
model is trained on a 3D skeletal dataset (NTU RGBD).  I see that in
"ntu_read_skeleton.py", you extract 3D coordinates (x,y,z) from the raw
skeleton data. So, In order to test this model on 2D skeletal data, I
should train the model also in 2D skeletal data right?

Apart from changing the default input channel in model from 3 to 2, should
I also edit the function "read_xyz" in  "ntu_read_skeleton.py" to extract
only 2D coordinates from NTU RGBD raw skeletal data instead of 3D
coordinates before training? Please advise.

Your help on this would be highly appreciated.


*Yours sincerely*
*Jagadish Kumaran Jayagopal*
UIN:822007030
